name = "main"

[public_repo]
repo      = "RealHarshThakur/demo-app-branches"
directory = "."
branch    = "main"

[[install_groups]]
name  = "staging"
order = 1
[install_groups.label_selector]
env = "staging"

[[install_groups]]
name  = "prod"
order = 2
[install_groups.label_selector]
env = "prod"
